# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 23, 9, 51, 51, 317000, tzinfo=utc)),
        ),
    ]
